# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-06 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_auto_20170103_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='url',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
